print("lista de tipos  sanguíneos:")
print(" ")
print("[ A+    ]")
print("[ A-     ]")
print("[ B+    ]")
print("[ B-     ]")
print("[ AB+ ]")
print("[ AB-  ]")
print("[ O+    ]")
print("[ O-     ]")
print(" ")
sangue = str(input("qual seu tipo sanguíneo? "))
if sangue == "a+":
   print(" ")
   print("o tipo de sangue ({}) pode receber A+, A-, O+ e O-".format(sangue))
   print("o tipo de sangue ({}) pode doar para AB+ e A-".format(sangue))
   print(" ")
if sangue == "a-":
   print(" ")
   print("o tipo de sangue ({}) pode receber A- e O-".format(sangue))
   print("o tipo de sangue ({}) pode doar para A+, A-, AB+ e AB-".format(sangue))
   print(" ")
if sangue == "b+":
   print(" ")
   print("o tipo de sangue ({}) pode receber B+, B-, O+ e O-".format(sangue))
   print("o tipo de sangue ({}) pode doar para B+ e AB+".format(sangue))
   print(" ")
if sangue == "b-":
   print(" ")
   print("o tipo de sangue ({}) pode receber B- e O-".format(sangue))
   print("o tipo de sangue ({}) pode doar para B+, B-, A+ e AB-".format(sangue))
   print(" ")
if sangue == "ab+":
   print(" ")
   print("o tipo de sangue ({}) pode receber todos os tipos.".format(sangue))
   print("o tipo de sangue ({}) pode doar para AB".format(sangue))
   print(" ")
if sangue == "ab-":
   print(" ")
   print("o tipo de sangue ({}) pode receber A-, B-, O- e AB-".format(sangue))
   print("o tipo de sangue ({}) pode doar para AB+ e AB-".format(sangue))
   print(" ")
if sangue == "o+":
   print(" ")
   print("o tipo de sangue ({}) pode receber O + e O-".format(sangue))
   print("o tipo de sangue ({}) pode doar para A+, B+,O+ e AB+".format(sangue))
   print(" ")
if sangue == "o-":
   print(" ")
   print("o tipo de sangue ({}) pode receber O-".format(sangue))
   print("o tipo de sangue ({}) pode doar para todos os tipos.".format(sangue))
   print(" ")
